# -----------------------------
# Prefix
# -----------------------------
unbind C-b
set -g prefix C-a
bind C-a send-prefix

# -----------------------------
# General
# -----------------------------
set -g mouse on
set -g default-shell /bin/zsh
set -g default-terminal "tmux-256color"
set -ga terminal-overrides ",xterm-256color:RGB"
set -g xterm-keys on

# -----------------------------
# Splits
# -----------------------------
unbind '"'
unbind %
bind | split-window -h
bind - split-window -v

# -----------------------------
# Pane navigation (Option)
# -----------------------------
bind -n M-Left  select-pane -L
bind -n M-Right select-pane -R
bind -n M-Up    select-pane -U
bind -n M-Down  select-pane -D

# -----------------------------
# Window navigation (Command)
# -----------------------------
bind -n C-M-Left  previous-window
bind -n C-M-Right next-window

# -----------------------------
# Reload
# -----------------------------
bind r source-file ~/.tmux.conf \; display-message "Config reloaded"

# -----------------------------
# Copy mode (macOS)
# -----------------------------
bind -T copy-mode-vi y send -X copy-pipe-and-cancel "pbcopy"

# -----------------------------
# Plugins
# -----------------------------
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'
set -g @plugin 'dracula/tmux'
set -g @plugin 'tmux-plugins/tmux-yank'

# Dracula
set -g @dracula-plugins "cpu-usage network battery time"
set -g @dracula-show-timezone true
set -g @dracula-refresh-rate 5

run '~/.tmux/plugins/tpm/tpm'

