#List of plugins
 set -g @tpm_plugins '          \
   tmux-plugins/tpm             \
   tmux-plugins/tmux-sensible   \
   tmux-plugins/tmux-resurrect  \
 '
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'
set -g @plugin 'dracula/tmux'
set -g @plugin 'tmux-plugins/tmux-yank'
bind -T copy-mode    C-c send -X copy-pipe-no-clear "xsel -i --clipboard"
bind -T copy-mode-vi C-c send -X copy-pipe-no-clear "xsel -i --clipboard"

# available plugins: battery, cpu-usage, gpu-usage, ram-usage, network, network-bandwith, weather,  time
set -g @dracula-plugins "cpu-usage ram-usage network time"
# available colors: white, gray, dark_gray, light_purple, dark_purple, cyan, green, orange, red, pink, yellow
# set -g @dracula-[plugin-name]-colors "[background] [foreground]"
set -g @dracula-cpu-usage-colors "pink dark_gray"
set -g @dracula-ram-usage-colors "green dark_gray"
set -g @dracula-network-colors "dark_purple yellow"
set -g @dracula-time-colors "cyan gray"
set -g @dracula-show-timezone false
set -g @dracula-day-month true
set -g @dracula-refresh-rate 1
set -g @dracula-border-contrast true

# Default shell is bash
set-option -g default-command "exec /bin/bash"

# remap prefix from 'C-b' to 'C-a'
unbind C-b
set-option -g prefix C-a
bind-key C-a send-prefix

# split panes using | and -
bind | split-window -h
bind - split-window -v
unbind '"'
unbind %

# Shift arrow to switch windows
bind -n S-Left  previous-window
bind -n S-Right next-window

# moving windows using arrows
bind-key -n C-S-Left swap-window -t -1
bind-key -n C-S-Right swap-window -t +1

# reload config file (change file location to your the tmux.conf you want to use)
bind r source-file ~/.tmux/tmux.conf

# switch panes using Alt-arrow without prefix
bind -n M-Left select-pane -L
bind -n M-Right select-pane -R
bind -n M-Up select-pane -U
bind -n M-Down select-pane -D

# Enable mouse
set -g mouse on

# Colors
set -g default-terminal "xterm-256color"


 # Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run  '~/.tmux/plugins/tpm/tpm'
run-shell ~/.tmux/plugins/tmux-resurrect/resurrect.tmux
run-shell ~/.tmux/plugins/tmux-continuum/continuum.tmux

